 export const ProductsInArray = [
    {
        name:"abrazadera",
        quantity:1,
        img:"/abrazadera.webp",
        price:25,
        id:1
    },
    {
        name:"retenes",
        quantity:1,
        img:"/retenes.png",
        price:32,
        id:2
    },
    {
        name:"sello doble cartucho",
        quantity:1,
        img:"/sello-doble.png",
        price:100,
        id:3
    },
    {
        name:"billas",
        quantity:1,
        img:"/billas.png",
        price:50,
        id:4
    },
    {
        name:"oring",
        quantity:1,
        img:"/oring.png",
        price:30,
        id:5
    },
    {
        name:"empaquetadura",
        quantity:1,
        img:"/empaquetadura.png",
        price:40,
        id:6
    },
    {
        name:"segers",
        quantity:1,
        img:"/seeger.png",
        price:25,
        id:7
    },
    {
        name:"pines",
        quantity:1,
        img:"/pines.png",
        price:35,
        id:8
    },
    {
        name:"sellos",
        quantity:1,
        img:"/sellos-mecanicos.png",
        price:80,
        id:9
    },
    {
        name:"abrazadera industrial",
        quantity:1,
        img:"/abrazadera-industrial.png",
        price:80,
        id:10
    },
    {
        name:"abrazadera de perno",
        quantity:1,
        img:"/abrazadera-perno.png",
        price:70,
        id:11
    },
    {
        name:"graseras",
        quantity:1,
        img:"/graseras.png",
        price:60,
        id:12
    },
    

 ] 